spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/projectenv
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  application:
    name: project-env

outbox:
  batch-size: 100
  pool-interval-ms: 10s
  initial-delay-ms: 0s
  attempt-limit: 3
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    client-id: project-env-events-client
    topics:
      - name: project-env-events
        partitions: 3
        replication-factor: 1
    props:
      spring.json.add.type.headers: true

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG

server:
  port: 8081

